import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";
import Providers from "./providers/Providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased dark`}
    >
      <Providers>
        <body className="min-h-screen flex flex-col bg-black text-zinc-100 antialiased selection:bg-blue-600 selection:text-white">
          <Navbar />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </body>
      </Providers>
    </html>
  );
}
